language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - android-sdk-license.*
jdk:
- oraclejdk8
sudo: false
before_install:
- chmod +x gradlew
- chmod +x travis-build.sh
script: "./travis-build.sh"
after_success: 
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"
addons:
  coverity_scan:
    project:
      name: manukn/Glide-ImageView-with-progress-bar
      description: Build submitted via Travis CI
    notification_email: me@manuknarayanan.com
    branch_pattern: coverity_scan
env:
  global:
  - secure: kMSdY2xvtaCsAS3bgYpXGC9803SbEqLgVFgHkBsk0iVnYeR2KjyXb9Q2jxsUGe+og8hMHkaGLir7AhVXBrXLeiimayTomhk3NhK0JQVya76lwemq2/6NNW55lP1Qy9CF5BySnK4m9/JTOn0yBFooQfMV4JcLR1TQ2Bxb9c8WOnKGZUh9ivWBrdiepxrLTiacME+dfNC/LnVjODOTfF0B5AZ5RO/imcVMmBLqxVLXOX+YOGG3K0SgkMa8GNkK5O31D5IqaMcWoXQaz+83x3zCV6JsPfEU2xHaln3Mk1A40QtfDwMfBM8z/8r4tjBIICwDiVJuh/OUBij83ohLjH9mU7ahGf8e+d3DO1lDd0DWkizfrFbpH064ikeaKcNHM8um1Po+RcEF+0MUleYhRVjlBqsvpOcbd6JvgkuDs0LGu6+k/4SnwkR2zCECjjaCKm+6nG6DhrC0Jnwd5VdKHbj0ciwk3ESdv2o+roFZ6P0sNioQP89WKscqwYM1mIvBogHvZP/AOOVRAvoi8Ofwx8WO/1u6e7U5OoaDzLuXB/Sd+HvowrMiLT4UPgPVf9K02QI0ojVFLu9EWavfYbJ37dvPBt+52jfRv8ndlHDNd3Dsa4z3CLvjLtY0hwQmbmDSuRT1s3WY70rYXEEfdX3qDgZBjyIUehW8rFzBYcGmX75goe4=
  - secure: rHvpTGwZPnfY80XUDq6PT9qOIoCjPTfGFuf8bW3Qrc2NVD4xfsc9oCeNc1ToYg4gHp+mVAx487Y5T5ADJkObCT5mEhW0FEA8hNRAZaOLrCd9yrXdthkMf3l1UbpcnLwb1u528rNzbVLLUtRf6nTVu/8h4EjVoIfjqf/d1tTE15rSqmduKYdEWiecpvtCKdWhewVJyDJIF9sMFp4NZX9F9lB5fNaUn++W3FlXpObqSOx91GaN6e6/9SsVqSbU9zmRgBGtw8p+9a0RSpu7CNnvhmh+Qx5hLh+FTyS7vZdR1gM3KazMRlNEkYw3w/4ULuxeTRljMLAcgPJD8vQxaJ2rQ81kd5OECrZkn9rx+Hja9/zdFP3MIOJyML5jKZNY0cahEHawPY4mNFiAX5BvISYfNmPYYaoz48oQYN/GqAg34AuMLWv3NxWE9S/DvthAF9VqZgZjtfRXcyElDUo63yrV+/D5aNliFjnUDRBBnudnPrS6C+Ts2hr3O06nJSrTI6Q7zmf0DoeZyFSdlBsxIjFckEqe75ST6llNwZR/QLOggn/CBdi8xWMy9sgPBNK3JAAsiuKqUwYI1pVo08x9lUixBusnsnkY7bhM6q/IELFJe1OSEjHsEeXD55AuQocGMOkF84Rs+4OmhBrORT2948W2NBz3Z5vlMBAhwsgB8STv1Pg=
